BLOCKS = {
    'Solapur,Madha': 1,
    'Solapur,Akkalkot': 2,
    'Solapur,Solapur South': 3,
    'Solapur,Pandharpur': 4,
    'Solapur,Mohol': 5,
    'Pune,Bhor': 6,
    'Pune,Baramati': 7,
    'Pune,Daund': 8,
    'Pune,Mulshi': 9,
    'Pune,Khed': 10,
    'Ahmednagar,Nagar': 11,
    'Ahmednagar,Shevgaon': 12,
    'Ahmednagar,Rahuri': 13,
    'Ahmednagar,Nevasa': 14,
    'Ahmednagar,Sangamner': 15,
    'Ahmednagar,Karjat': 16,
    'Ahmednagar,Pathardi': 17,
    'Ahmednagar,Shrigonda': 18,
    'Ahmednagar,Kopargaon': 19,
    'Ahmednagar,Rahata': 20,
    'Ahmednagar,Shrirampur': 21,
    'Ahmednagar,Parner': 22,
    'Aurangabad,Aurangabad': 23,
    'Aurangabad,Paithan': 24,
    'Aurangabad,Phulambri': 25,
    'Aurangabad,khultabad': 26,
    'Aurangabad,Gangapur': 27,
    'Amravati,Chandurbazar': 28,
    'Amravati,Morshi': 29,
    'Amravati,Nandgaon-Khandeshwar': 30,
    'Amravati,Amravati': 31,
    'Amravati,Bhatkuli': 32,
}  # (s_q5)
